version: "3.9"
services:
  db:
    image: iamtopcat/postgres:master-b71
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: beatmaps
      POSTGRES_USER: beatmaps
      POSTGRES_PASSWORD: "insecure-password"
    restart: always

  rabbitmq:
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - ./rabbitmq_data:/var/lib/rabbitmq/mnesia
      environment:
        RABBITMQ_DEFAULT_USER: bandspace
        RABBITMQ_DEFAULT_PASS: bandspaceRabbitmq
      restart: always

volumes:
      rabbitmq_data:
        driver: local







